### ISSUE TITLE
Add support for  resources apart from pods

### ISSUE THREAD

**Issue by sambhav** [dlorenc/cosigned#6]
It might be possible to add support for verifying that resources other than pods also reference images which are signed. This could possibly be done by providing the controller a configmap that contains the custom resource's gvk and the jsonpath to the field in the resource which makes up the image reference(s) .

For eg.

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/ 

The config for the above might look like -
```yaml
imageFields:
  - apiVersion: batch/v1
    kind: CronJob
    field: ".spec.jobTemplate.spec.template.spec.containers[*].image"
```
